---
swagger: "2.0"
info:
  description: Test API pour WS Swagger / OpenAPI
  version: 0.0.5
  title: TestAPI
  termsOfService: http://localhost:8080/swagger-ui.html
  contact:
    name: Philippe Bousquet
    url: http://sqli.com
    email: pbousquet@sqli.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
basePath: /
tags:
- name: goodbye
  description: Goodbye API
consumes:
- application/json
produces:
- application/json
paths:
  /api/v1/goodbye:
    get:
      tags:
      - goodbye
      summary: goodbye
      operationId: goodbyeUsingGET_1
      parameters: []
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoodbyeDto'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/goodbye/{name}:
    get:
      tags:
      - goodbye
      summary: goodbye
      operationId: goodbyeUsingGET
      parameters:
      - name: name
        in: path
        description: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoodbyeDto'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
definitions:
  GoodbyeDto:
    type: object
    properties:
      message:
        type: string
    title: GoodbyeDto
