---
swagger: "2.0"
info:
  description: Test API pour WS Swagger / OpenAPI
  version: 0.0.5
  title: TestAPI
  termsOfService: http://localhost:8080/swagger-ui.html
  contact:
    name: Philippe Bousquet
    url: http://sqli.com
    email: pbousquet@sqli.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
basePath: /
tags:
- name: hello
  description: Hello API
consumes:
- application/json
produces:
- application/json
paths:
  /api/v1/hello:
    get:
      tags:
      - hello
      summary: Saluer le monde
      operationId: helloUsingGET_1
      parameters: []
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HelloDto'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/hello/{name}:
    get:
      tags:
      - hello
      summary: Saluer une personne en particulier
      operationId: helloUsingGET
      parameters:
      - name: name
        in: path
        description: Nom de la personne à saluer
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HelloDto'
        "400":
          description: Mauvaise requête, 123 n'est pas une valeurs valide
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
definitions:
  HelloDto:
    type: object
    properties:
      message:
        type: string
    title: HelloDto
